---
/**:
  controller_manager:
    ros__parameters:
      update_rate: 50

      # joint_state_broadcaster:
      #   type: joint_state_broadcaster/JointStateBroadcaster

      robotnik_base_control:
        type: mecanum_drive_controller/MecanumDriveController        

      joint_trajectory_controller:
        type: joint_trajectory_controller/JointTrajectoryController
        
  robotnik_base_control:
    ros__parameters:
      use_sim_time: true
      
      front_left_wheel_command_joint_name: $(var robot_id)_front_left_wheel_joint
      front_right_wheel_command_joint_name: $(var robot_id)_front_right_wheel_joint
      rear_left_wheel_command_joint_name: $(var robot_id)_back_left_wheel_joint
      rear_right_wheel_command_joint_name: $(var robot_id)_back_right_wheel_joint

      kinematics:
        base_frame_offset: {x: 0.0, y: 0.0, theta: 0.0}
        wheels_radius: 0.11
        sum_of_robot_center_projection_on_X_Y_axis: 0.464

      publish_rate: 50.0
      odom_frame_id: $(var robot_id)_odom
      base_frame_id: $(var robot_id)_base_footprint
      pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.03]
      twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.03]
      enable_odom_tf: true

      reference_timeout: 0.5

  joint_trajectory_controller:
    ros__parameters:
      publish_rate: 50
      joints:
        - $(var robot_id)_arm_shoulder_pan_joint
        - $(var robot_id)_arm_shoulder_lift_joint
        - $(var robot_id)_arm_elbow_joint
        - $(var robot_id)_arm_wrist_1_joint
        - $(var robot_id)_arm_wrist_2_joint
        - $(var robot_id)_arm_wrist_3_joint

      command_interfaces:
        - position

      state_interfaces:
        - position
        - velocity

      state_publish_rate: 50.0
      action_monitor_rate: 20.0

      allow_partial_joints_goal: false
      open_loop_control: true
