/**:
  sfgenerator:
    ros__parameters:
      use_sim_time: true
      filter_plugins: ['voxel_downsample', stat_outlier_removal]
      stat_outlier_removal:
        plugin: 'sfframework/StatisticalOutlierRemovalFilter'
        nb_neighbors: 30
        std_ratio: 2.0
      voxel_downsample:
        plugin: 'sfframework/VoxelDownSampleFilter'
        voxel_size: 0.2
      partitioner_plugins: ['ransac', 'dbscan']
      ransac:
        plugin: 'sfframework/RansacSegmentation'
        distance_threshold: 0.1
      dbscan:
        input_tags: ['ground']
        invert_selection: true
        plugin: 'sfframework/DBSCAN'

      partitioned_pointcloud_visualization:
        display_outliers: true
        display_inliers: true
        inliers_considered: ['ground', 'clusters']
        colors:
          outliers:
            min: [255, 255, 255]
          ground:
            min: [57, 196, 94]
          clusters:
            min: [127, 0, 0]
            max: [255, 255, 0]
