/**:
  sfgenerator:
    ros__parameters:
      use_sim_time: true
      filter_plugins: ['stat_outlier_removal', 'voxel_downsample']
      stat_outlier_removal:
        plugin: 'sfframework/StatisticalOutlierRemovalFilter'
        nb_neighbors: 30
        std_ratio: 2.0
      voxel_downsample:
        plugin: 'sfframework/VoxelDownSampleFilter'
        voxel_size: 0.2
      partitioner_plugins: ['ransac']
      ransac:
        plugin: 'sfframework/RansacSegmentation'

      partitioned_pointcloud_visualization:
        display_outliers: true
        display_inliers: true
        inliers_considered: ["ground"]
        colors:
          outliers:
            min: [255, 255, 255]
          ground:
            min: [57, 196, 94]
